// Code generated by tool. DO NOT EDIT.
package pb

import(
	"framework/proto/pb/cs"
)


var CsMsgArray [][4]interface{} = [][4]interface{}{
	// rpc
	{1, int(cs.CsGate_msg_id_req_heart_beat), &cs.ReqHeartBeat{}, &cs.RespHeartBeat{}},
	{1, int(cs.CsGate_msg_id_req_login_gate), &cs.ReqLoginGate{}, &cs.RespLoginGate{}},
	// rpc notify
	{0, int(cs.CsGate_msg_id_notify_tooltip), &cs.NotifyTooltip{}, nil},
}