// Code generated by tool. DO NOT EDIT.
package pb

import (
	"framework/proto/pb/cs"
	"framework/proto/pb/ss"
)

var CSRpcMsg [][]any = [][]any{
	//cs_gate
	{int(cs.CsGate_msg_id_req_heart_beat), &cs.ReqHeartBeat{}, &cs.RespHeartBeat{}},
	{int(cs.CsGate_msg_id_req_login_gate), &cs.ReqLoginGate{}, &cs.RespLoginGate{}},
	//cs_player
	{int(cs.CsPlayer_msg_id_req_query_player), &cs.ReqQueryPlayer{}, &cs.RespQueryPlayer{}},
}

var SSRpcMsg [][]any = [][]any{
	//ss_mysql_proxy
	{int(ss.SsMysqlProxy_msg_id_req_execute_sql), &ss.ReqExecuteSql{}, &ss.RespExecuteSql{}},
	//ss_redis_proxy
	{int(ss.SsRedisProxy_msg_id_req_redis_cmd), &ss.ReqRedisCmd{}, &ss.RespRedisCmd{}},
	{int(ss.SsRedisProxy_msg_id_req_redis_eval), &ss.ReqRedisEval{}, &ss.RespRedisEval{}},
	//ss_player
	{int(ss.SsPlayer_msg_id_req_player_login), &ss.ReqPlayerLogin{}, &ss.RespPlayerLogin{}},
	{int(ss.SsPlayer_msg_id_req_player_logout), &ss.ReqPlayerLogout{}, &ss.RespPlayerLogout{}},
}
