// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: ss_rank.proto

package ss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//消息ID定义[范围50000-50999]
type SsRank int32

const (
	SsRank_msg_id_req_sync_rank_score SsRank = 50000
)

// Enum value maps for SsRank.
var (
	SsRank_name = map[int32]string{
		50000: "msg_id_req_sync_rank_score",
	}
	SsRank_value = map[string]int32{
		"msg_id_req_sync_rank_score": 50000,
	}
)

func (x SsRank) Enum() *SsRank {
	p := new(SsRank)
	*p = x
	return p
}

func (x SsRank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SsRank) Descriptor() protoreflect.EnumDescriptor {
	return file_ss_rank_proto_enumTypes[0].Descriptor()
}

func (SsRank) Type() protoreflect.EnumType {
	return &file_ss_rank_proto_enumTypes[0]
}

func (x SsRank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SsRank) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SsRank(num)
	return nil
}

// Deprecated: Use SsRank.Descriptor instead.
func (SsRank) EnumDescriptor() ([]byte, []int) {
	return file_ss_rank_proto_rawDescGZIP(), []int{0}
}

//玩家属性变更时同步rank数据
type ReqSyncRankScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid      *int64 `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	RankType  *int32 `protobuf:"varint,2,opt,name=rank_type,json=rankType" json:"rank_type,omitempty"`
	RankScore *int64 `protobuf:"varint,3,opt,name=rank_score,json=rankScore" json:"rank_score,omitempty"`
}

func (x *ReqSyncRankScore) Reset() {
	*x = ReqSyncRankScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSyncRankScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSyncRankScore) ProtoMessage() {}

func (x *ReqSyncRankScore) ProtoReflect() protoreflect.Message {
	mi := &file_ss_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSyncRankScore.ProtoReflect.Descriptor instead.
func (*ReqSyncRankScore) Descriptor() ([]byte, []int) {
	return file_ss_rank_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSyncRankScore) GetGuid() int64 {
	if x != nil && x.Guid != nil {
		return *x.Guid
	}
	return 0
}

func (x *ReqSyncRankScore) GetRankType() int32 {
	if x != nil && x.RankType != nil {
		return *x.RankType
	}
	return 0
}

func (x *ReqSyncRankScore) GetRankScore() int64 {
	if x != nil && x.RankScore != nil {
		return *x.RankScore
	}
	return 0
}

type RespSyncRankScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
}

func (x *RespSyncRankScore) Reset() {
	*x = RespSyncRankScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSyncRankScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSyncRankScore) ProtoMessage() {}

func (x *RespSyncRankScore) ProtoReflect() protoreflect.Message {
	mi := &file_ss_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSyncRankScore.ProtoReflect.Descriptor instead.
func (*RespSyncRankScore) Descriptor() ([]byte, []int) {
	return file_ss_rank_proto_rawDescGZIP(), []int{1}
}

func (x *RespSyncRankScore) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *RespSyncRankScore) GetErrDesc() string {
	if x != nil && x.ErrDesc != nil {
		return *x.ErrDesc
	}
	return ""
}

var File_ss_rank_proto protoreflect.FileDescriptor

var file_ss_rank_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x73, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x73, 0x73, 0x22, 0x65, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f,
	0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x72, 0x61, 0x6e, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x4c, 0x0a, 0x14, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x44, 0x65, 0x73, 0x63, 0x2a, 0x2b, 0x0a, 0x07, 0x73, 0x73, 0x5f, 0x72,
	0x61, 0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x1a, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x10, 0xd0, 0x86, 0x03,
}

var (
	file_ss_rank_proto_rawDescOnce sync.Once
	file_ss_rank_proto_rawDescData = file_ss_rank_proto_rawDesc
)

func file_ss_rank_proto_rawDescGZIP() []byte {
	file_ss_rank_proto_rawDescOnce.Do(func() {
		file_ss_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_ss_rank_proto_rawDescData)
	})
	return file_ss_rank_proto_rawDescData
}

var file_ss_rank_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ss_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ss_rank_proto_goTypes = []interface{}{
	(SsRank)(0),               // 0: ss.ss_rank
	(*ReqSyncRankScore)(nil),  // 1: ss.req_sync_rank_score
	(*RespSyncRankScore)(nil), // 2: ss.resp_sync_rank_score
}
var file_ss_rank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ss_rank_proto_init() }
func file_ss_rank_proto_init() {
	if File_ss_rank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ss_rank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSyncRankScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_rank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespSyncRankScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ss_rank_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ss_rank_proto_goTypes,
		DependencyIndexes: file_ss_rank_proto_depIdxs,
		EnumInfos:         file_ss_rank_proto_enumTypes,
		MessageInfos:      file_ss_rank_proto_msgTypes,
	}.Build()
	File_ss_rank_proto = out.File
	file_ss_rank_proto_rawDesc = nil
	file_ss_rank_proto_goTypes = nil
	file_ss_rank_proto_depIdxs = nil
}
