// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: cs_player.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//消息ID定义[范围1101-1200],见cs_comon::msg_route
type CsPlayer int32

const (
	CsPlayer_msg_id_req_query_player CsPlayer = 1101
)

// Enum value maps for CsPlayer.
var (
	CsPlayer_name = map[int32]string{
		1101: "msg_id_req_query_player",
	}
	CsPlayer_value = map[string]int32{
		"msg_id_req_query_player": 1101,
	}
)

func (x CsPlayer) Enum() *CsPlayer {
	p := new(CsPlayer)
	*p = x
	return p
}

func (x CsPlayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CsPlayer) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_player_proto_enumTypes[0].Descriptor()
}

func (CsPlayer) Type() protoreflect.EnumType {
	return &file_cs_player_proto_enumTypes[0]
}

func (x CsPlayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CsPlayer) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CsPlayer(num)
	return nil
}

// Deprecated: Use CsPlayer.Descriptor instead.
func (CsPlayer) EnumDescriptor() ([]byte, []int) {
	return file_cs_player_proto_rawDescGZIP(), []int{0}
}

// 查询玩家基础信息
type ReqQueryPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId *int64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (x *ReqQueryPlayer) Reset() {
	*x = ReqQueryPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryPlayer) ProtoMessage() {}

func (x *ReqQueryPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_cs_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryPlayer.ProtoReflect.Descriptor instead.
func (*ReqQueryPlayer) Descriptor() ([]byte, []int) {
	return file_cs_player_proto_rawDescGZIP(), []int{0}
}

func (x *ReqQueryPlayer) GetPlayerId() int64 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

type RespQueryPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
}

func (x *RespQueryPlayer) Reset() {
	*x = RespQueryPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespQueryPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespQueryPlayer) ProtoMessage() {}

func (x *RespQueryPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_cs_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespQueryPlayer.ProtoReflect.Descriptor instead.
func (*RespQueryPlayer) Descriptor() ([]byte, []int) {
	return file_cs_player_proto_rawDescGZIP(), []int{1}
}

func (x *RespQueryPlayer) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *RespQueryPlayer) GetErrDesc() string {
	if x != nil && x.ErrDesc != nil {
		return *x.ErrDesc
	}
	return ""
}

var File_cs_player_proto protoreflect.FileDescriptor

var file_cs_player_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x63, 0x73, 0x22, 0x2f, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x44, 0x65, 0x73,
	0x63, 0x2a, 0x29, 0x0a, 0x09, 0x63, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x17, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0xcd, 0x08,
}

var (
	file_cs_player_proto_rawDescOnce sync.Once
	file_cs_player_proto_rawDescData = file_cs_player_proto_rawDesc
)

func file_cs_player_proto_rawDescGZIP() []byte {
	file_cs_player_proto_rawDescOnce.Do(func() {
		file_cs_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_player_proto_rawDescData)
	})
	return file_cs_player_proto_rawDescData
}

var file_cs_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cs_player_proto_goTypes = []interface{}{
	(CsPlayer)(0),           // 0: cs.cs_player
	(*ReqQueryPlayer)(nil),  // 1: cs.req_query_player
	(*RespQueryPlayer)(nil), // 2: cs.resp_query_player
}
var file_cs_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cs_player_proto_init() }
func file_cs_player_proto_init() {
	if File_cs_player_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespQueryPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_player_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_player_proto_goTypes,
		DependencyIndexes: file_cs_player_proto_depIdxs,
		EnumInfos:         file_cs_player_proto_enumTypes,
		MessageInfos:      file_cs_player_proto_msgTypes,
	}.Build()
	File_cs_player_proto = out.File
	file_cs_player_proto_rawDesc = nil
	file_cs_player_proto_goTypes = nil
	file_cs_player_proto_depIdxs = nil
}
