// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: cs_rank.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//消息ID定义[范围2000-2999]
type CsRank int32

const (
	CsRank_msg_id_req_query_rank_info CsRank = 2000
)

// Enum value maps for CsRank.
var (
	CsRank_name = map[int32]string{
		2000: "msg_id_req_query_rank_info",
	}
	CsRank_value = map[string]int32{
		"msg_id_req_query_rank_info": 2000,
	}
)

func (x CsRank) Enum() *CsRank {
	p := new(CsRank)
	*p = x
	return p
}

func (x CsRank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CsRank) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_rank_proto_enumTypes[0].Descriptor()
}

func (CsRank) Type() protoreflect.EnumType {
	return &file_cs_rank_proto_enumTypes[0]
}

func (x CsRank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CsRank) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CsRank(num)
	return nil
}

// Deprecated: Use CsRank.Descriptor instead.
func (CsRank) EnumDescriptor() ([]byte, []int) {
	return file_cs_rank_proto_rawDescGZIP(), []int{0}
}

type ReqQueryRankInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqQueryRankInfo) Reset() {
	*x = ReqQueryRankInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQueryRankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQueryRankInfo) ProtoMessage() {}

func (x *ReqQueryRankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cs_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQueryRankInfo.ProtoReflect.Descriptor instead.
func (*ReqQueryRankInfo) Descriptor() ([]byte, []int) {
	return file_cs_rank_proto_rawDescGZIP(), []int{0}
}

type RespQueryRankInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
}

func (x *RespQueryRankInfo) Reset() {
	*x = RespQueryRankInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespQueryRankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespQueryRankInfo) ProtoMessage() {}

func (x *RespQueryRankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cs_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespQueryRankInfo.ProtoReflect.Descriptor instead.
func (*RespQueryRankInfo) Descriptor() ([]byte, []int) {
	return file_cs_rank_proto_rawDescGZIP(), []int{1}
}

func (x *RespQueryRankInfo) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *RespQueryRankInfo) GetErrDesc() string {
	if x != nil && x.ErrDesc != nil {
		return *x.ErrDesc
	}
	return ""
}

var File_cs_rank_proto protoreflect.FileDescriptor

var file_cs_rank_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x73, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x63, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x4c, 0x0a, 0x14, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x44, 0x65, 0x73, 0x63, 0x2a, 0x2a, 0x0a, 0x07, 0x63, 0x73, 0x5f, 0x72,
	0x61, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x1a, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x10, 0xd0, 0x0f,
}

var (
	file_cs_rank_proto_rawDescOnce sync.Once
	file_cs_rank_proto_rawDescData = file_cs_rank_proto_rawDesc
)

func file_cs_rank_proto_rawDescGZIP() []byte {
	file_cs_rank_proto_rawDescOnce.Do(func() {
		file_cs_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_rank_proto_rawDescData)
	})
	return file_cs_rank_proto_rawDescData
}

var file_cs_rank_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cs_rank_proto_goTypes = []interface{}{
	(CsRank)(0),               // 0: cs.cs_rank
	(*ReqQueryRankInfo)(nil),  // 1: cs.req_query_rank_info
	(*RespQueryRankInfo)(nil), // 2: cs.resp_query_rank_info
}
var file_cs_rank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cs_rank_proto_init() }
func file_cs_rank_proto_init() {
	if File_cs_rank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_rank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQueryRankInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_rank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespQueryRankInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_rank_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_rank_proto_goTypes,
		DependencyIndexes: file_cs_rank_proto_depIdxs,
		EnumInfos:         file_cs_rank_proto_enumTypes,
		MessageInfos:      file_cs_rank_proto_msgTypes,
	}.Build()
	File_cs_rank_proto = out.File
	file_cs_rank_proto_rawDesc = nil
	file_cs_rank_proto_goTypes = nil
	file_cs_rank_proto_depIdxs = nil
}
